services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-check-thong-tin
    environment:
      - TZ=Etc/UTC
      - RESOLUTION=1366x768
    ports:
      - "6080:6080"  # noVNC (open in browser)
      - "5901:5901"  # VNC (optional)
    volumes:
      - ./data:/app/data
      - ./bigdata:/app/bigdata
    restart: unless-stopped
